version: '3.1'

services:
  app:
    image: '0c74c5c96431607ba0513497ec74d700df07699f2fb948d8eaf67b64f73cbd0c'
    container_name: app
    expose:
      - '8000'
    ports:
      - '8000:8000'
    environment:
      - DB_USER=dron
      - DB_PASSWORD=password
      - DB_URL= jdbc:postgresql://db:5432/
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: OwnerDb
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=dron
      - POSTGRES_PASSWORD=password